# Generated by Django 5.0.7 on 2024-08-21 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_category_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='tx_title', max_length=128, verbose_name='Title')),
                ('content', models.TextField(db_column='tx_content', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('author', models.ForeignKey(db_column='id_author', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Cadastro_Livro',
                'verbose_name_plural': 'Cadastros_Livros',
                'db_table': 'cadastro_livro',
                'managed': True,
            },
        ),
    ]
