# Generated by Django 5.0.7 on 2024-08-21 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cadastro_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cadastro_livro',
            name='category',
            field=models.ForeignKey(db_column='id_category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.category', verbose_name='Category'),
        ),
    ]
