# Generated by Django 5.0.7 on 2024-08-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_cadastro_livro_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
    ]
