# Generated by Django 5.0.7 on 2024-08-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nome_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tx_title', max_length=128, verbose_name='Name')),
                ('email', models.CharField(db_column='tx_name', verbose_name='Email')),
                ('password', models.CharField(db_column='tx_password', max_length=8, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Cadastro_Usuario',
                'verbose_name_plural': 'Cadastros_Usuarios',
                'db_table': 'cadastro_usuario',
                'managed': True,
            },
        ),
    ]
