# Generated by Django 5.0.7 on 2024-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cadastro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_usuario',
            name='image',
            field=models.ImageField(blank=True, db_column='tx_image', upload_to='', verbose_name='Imagem'),
        ),
    ]
