# Generated by Django 5.0.7 on 2024-08-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cadastro_usuario_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_usuario',
            name='image',
        ),
        migrations.AddField(
            model_name='cadastro_livro',
            name='criado_por',
            field=models.CharField(db_column='tx_author', default='valor_padrao', max_length=25, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='cadastro_livro',
            name='image',
            field=models.ImageField(blank=True, db_column='tx_image', upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='cadastro_livro',
            name='category',
            field=models.ForeignKey(db_column='id_category', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
