# Generated by Django 5.0.7 on 2024-08-21 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cadastro_usuario_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_livro',
            name='author',
            field=models.ForeignKey(db_column='id_author', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por:'),
        ),
    ]
