# Generated by Django 5.0.7 on 2024-08-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cadastro_livro_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_livro',
            name='description',
            field=models.CharField(db_column='text_description', default='valor_padrao', max_length=128, verbose_name='Description'),
        ),
    ]
