# Generated by Django 5.0.7 on 2024-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cadastro_livro_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_livro',
            name='price',
            field=models.CharField(db_column='tx_price', default='R$ 00,00', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cadastro_livro',
            name='criado_por',
            field=models.CharField(db_column='tx_author', default='Add', max_length=25, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='cadastro_livro',
            name='description',
            field=models.CharField(db_column='text_description', default='Add', max_length=128, verbose_name='Description'),
        ),
    ]
