# Generated by Django 5.0.7 on 2024-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cadastro_livro_price_alter_cadastro_livro_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_livro',
            name='image',
            field=models.ImageField(blank=True, db_column='tx_image', upload_to='livros/', verbose_name='Imagem'),
        ),
    ]
