# Generated by Django 5.0.7 on 2024-08-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cadastro_livro_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_livro',
            name='price',
        ),
    ]
